---
- name: "NVIM | Directory"
  file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory

- name: "NVIM | Symlink nvim directory"
  file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir}}/.config/nvim"
    state: link
    force: true
